[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Fusion-Create Discipline Dpcument"
authors = [{name = "schneik", email = "schneik@fastmail.com"}]
dynamic = ["version", "description"]
